import { FormEvent, ReactNode, useEffect, useState } from "react";
import { NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { ApiError, API_BASE_URL, api } from "./api";
import type { Analysis, AnalysisWithEmail, EmailInfo, ForensicReport, ForensicRun, ProviderObservation } from "./types";
import { dateTime, percent, verdictTone } from "./utils";

const cache = {
  get<T>(key: string): T | null { try { return JSON.parse(localStorage.getItem(key) || "null") as T | null; } catch { return null; } },
  set(key: string, value: unknown) { localStorage.setItem(key, JSON.stringify(value)); },
};

function Layout({ children }: { children: ReactNode }) {
  const links = [["/", "Dashboard"], ["/email-analysis", "Email Analysis"]] as const;
  return <div className="min-h-screen"><header className="border-b border-slate-800 bg-slate-950/80"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><NavLink to="/" className="text-lg font-bold text-cyan-400">SandBoxTrace</NavLink><nav className="flex gap-1">{links.map(([to, text]) => <NavLink key={to} to={to} className={({ isActive }) => `rounded-md px-3 py-2 text-sm ${isActive ? "bg-slate-800 text-white" : "text-slate-400 hover:text-white"}`}>{text}</NavLink>)}</nav></div></header><main className="mx-auto max-w-6xl px-4 py-8">{children}</main></div>;
}

function State({ loading, error, empty, children }: { loading?: boolean; error?: unknown; empty?: boolean; children?: ReactNode }) {
  if (loading) return <div className="panel text-slate-300">Loading investigation data…</div>;
  if (error) return <div className="panel border-rose-900 text-rose-200">{error instanceof ApiError ? error.message : "Unable to load this data. Check the API connection and try again."}</div>;
  if (empty) return <div className="panel text-slate-400">No investigation has been started yet.</div>;
  return <>{children}</>;
}

function Badge({ value }: { value: string }) { const tone = verdictTone(value); const styles = { safe: "bg-emerald-500/15 text-emerald-300", suspicious: "bg-amber-500/15 text-amber-300", malicious: "bg-rose-500/15 text-rose-300", neutral: "bg-slate-700 text-slate-300" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${styles[tone]}`}>{value.replace(/_/g, " ")}</span>; }
function Metric({ label, value }: { label: string; value: ReactNode }) { return <div className="panel"><p className="label">{label}</p><div className="mt-2 text-2xl font-semibold">{value}</div></div>; }
function ProviderCard({ item }: { item: ProviderObservation }) { return <div className="rounded-lg border border-slate-800 p-4"><div className="flex items-center justify-between"><strong className="capitalize">{item.provider}</strong><Badge value={item.status} /></div><pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap text-xs text-slate-400">{JSON.stringify(item.response, null, 2)}</pre></div>; }

function Dashboard() {
  const [health, setHealth] = useState<"checking" | "online" | "offline">("checking");
  const analysis = cache.get<AnalysisWithEmail>("lastAnalysis"); const run = cache.get<ForensicRun>("lastRun");
  useEffect(() => { api.health().then(() => setHealth("online")).catch(() => setHealth("offline")); }, []);
  return <section className="space-y-6"><div><p className="label">Phase 1–3 investigation console</p><h1 className="mt-2 text-3xl font-bold">Email threat intelligence</h1><p className="mt-2 max-w-2xl text-slate-400">Upload an email, review extracted URLs, then render a target in the isolated browser to collect VLM, threat-intelligence, and infrastructure evidence.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Backend" value={<Badge value={health} />} /><Metric label="Email phishing probability" value={analysis ? percent(analysis.email_phishing_probability) : "—"} /><Metric label="Last verdict" value={run ? <Badge value={run.verdict} /> : "—"} /></div><div className="panel"><h2 className="font-semibold">Current investigation</h2>{analysis ? <div className="mt-3 space-y-2 text-sm text-slate-300"><p><span className="text-slate-500">Subject: </span>{analysis.email.subject || "(no subject)"}</p><p><span className="text-slate-500">Sender: </span>{analysis.email.sender || "Unknown"}</p><p><span className="text-slate-500">URL phishing probability: </span>{percent(analysis.url_phishing_probability)}</p><NavLink className="text-cyan-400 hover:text-cyan-300" to={`/analyses/${analysis.id}`}>Open analysis details →</NavLink>{run && <><span className="text-slate-600"> · </span><NavLink className="text-cyan-400 hover:text-cyan-300" to={`/forensics/${run.id}`}>Open forensics →</NavLink></>}</div> : <div className="mt-3"><NavLink className="button" to="/email-analysis">Analyze an .eml file</NavLink></div>}</div></section>;
}

function EmailAnalysis() {
  const navigate = useNavigate(); const [file, setFile] = useState<File | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) return setError("Choose an .eml file first."); setLoading(true); setError(null); try { const result = await api.analyzeEmail(file); cache.set("lastAnalysis", result); navigate(`/analyses/${result.id}`); } catch (err) { setError(err instanceof Error ? err.message : "Upload failed"); } finally { setLoading(false); } }
  return <section className="mx-auto max-w-2xl space-y-6"><div><p className="label">Phase 1</p><h1 className="mt-2 text-3xl font-bold">Email analysis</h1><p className="mt-2 text-slate-400">The original `.eml` is parsed and classified by the existing backend. No email content is analyzed in the browser.</p></div><form className="panel space-y-4" onSubmit={submit}><label className="block"><span className="label">RFC 822 message</span><input className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm file:mr-4 file:rounded-md file:border-0 file:bg-cyan-500 file:px-3 file:py-1.5 file:font-medium" type="file" accept=".eml,message/rfc822" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>{error && <p className="text-sm text-rose-300">{error}</p>}<button className="button" disabled={loading}>{loading ? "Analyzing…" : "Upload and analyze"}</button></form></section>;
}

function AnalysisDetails() {
  const { analysisId = "" } = useParams(); const navigate = useNavigate(); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [email, setEmail] = useState<EmailInfo | null>(null); const [error, setError] = useState<unknown>(); const [loading, setLoading] = useState(true); const [running, setRunning] = useState<string | null>(null);
  useEffect(() => { let active = true; (async () => { try { const detail = await api.analysis(analysisId); const saved = cache.get<AnalysisWithEmail>("lastAnalysis"); const message = saved?.id === detail.id ? saved.email : await api.email(detail.email_id); if (active) { setAnalysis(detail); setEmail(message); } } catch (err) { if (active) setError(err); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [analysisId]);
  async function inspect(urlId: string) { setRunning(urlId); try { const run = await api.startForensics(analysisId, urlId); cache.set("lastRun", run); navigate(`/forensics/${run.id}`); } catch (err) { setError(err); } finally { setRunning(null); } }
  if (loading) return <State loading />;
  if (error) return <State error={error} />;
  if (!analysis || !email) return <State empty />;
  return <section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label">Phase 1 results</p><h1 className="mt-2 text-3xl font-bold">Analysis details</h1></div><Badge value={analysis.label} /></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Phishing probability" value={percent(analysis.phishing_probability)} /><Metric label="Model confidence" value={percent(analysis.confidence)} /><Metric label="Created" value={<span className="text-sm">{dateTime(analysis.created_at)}</span>} /></div><div className="panel"><p className="label">Message</p><h2 className="mt-2 text-xl font-semibold">{email.subject || "(no subject)"}</h2><p className="mt-1 text-slate-400">{email.sender || "Unknown sender"}</p><p className="mt-4 whitespace-pre-wrap text-sm text-slate-300">{email.text_body || "No plaintext body"}</p></div><div className="panel"><div className="flex items-center justify-between"><div><p className="label">Phase 2 and 3</p><h2 className="mt-1 text-xl font-semibold">Extracted URLs</h2></div><span className="text-sm text-slate-400">Select a URL for isolated browser forensics</span></div><div className="mt-4 divide-y divide-slate-800">{email.urls.length ? email.urls.map((url) => <div className="flex flex-wrap items-center justify-between gap-3 py-3" key={url.id}><div className="min-w-0"><p className="truncate text-sm text-cyan-300">{url.url}</p><p className="text-xs text-slate-500">{url.domain}</p></div><button className="button-secondary text-sm" disabled={running !== null} onClick={() => inspect(url.id)}>{running === url.id ? "Collecting evidence…" : "Run forensics"}</button></div>) : <p className="py-4 text-slate-400">No URLs were extracted from this message.</p>}</div></div></section>;
}

function Forensics() {
  const { runId = "" } = useParams(); const [run, setRun] = useState<ForensicRun | null>(cache.get<ForensicRun>("lastRun")); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>();
  useEffect(() => { api.forensics(runId).then((value) => { setRun(value); cache.set("lastRun", value); }).catch(setError).finally(() => setLoading(false)); }, [runId]);
  return <State loading={loading} error={error} empty={!run}><section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="label">Phase 2 evidence fusion</p><h1 className="mt-2 text-3xl font-bold">Forensics</h1><p className="mt-2 break-all text-slate-400">{run!.url}</p></div><Badge value={run!.verdict} /></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Risk score" value={run!.risk_score.toFixed(1)} /><Metric label="Screenshot" value={run!.browser_observation?.screenshot_available ? "Captured" : "Unavailable"} /><Metric label="Final URL" value={<span className="text-sm">{run!.browser_observation?.final_url ? "Observed" : "Unavailable"}</span>} /></div><div className="grid gap-4 lg:grid-cols-2"><div className="panel"><h2 className="font-semibold">Browser signals</h2><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs text-slate-400">{JSON.stringify({ domains: run!.browser_observation?.domains, dom: run!.browser_observation?.dom_signals, javascript: run!.browser_observation?.javascript_signals }, null, 2)}</pre></div><div className="panel"><h2 className="font-semibold">Fused evidence</h2><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs text-slate-400">{JSON.stringify(run!.fused_evidence, null, 2)}</pre></div></div><div><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">Provider observations</h2><NavLink className="button-secondary text-sm" to={`/infrastructure/${run!.id}`}>Infrastructure intelligence</NavLink></div><div className="grid gap-4 lg:grid-cols-2">{run!.provider_observations.map((item) => <ProviderCard key={item.provider} item={item} />)}</div></div></section></State>;
}

function Infrastructure() {
  const { runId = "" } = useParams(); const [run, setRun] = useState<ForensicRun | null>(null); const [report, setReport] = useState<ForensicReport | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>();
  useEffect(() => { (async () => { try { const value = await api.forensics(runId); setRun(value); try { setReport(await api.report(runId)); } catch { /* API-key protected report can remain unavailable */ } } catch (err) { setError(err); } finally { setLoading(false); } })(); }, [runId]);
  const infrastructure = Array.isArray(run?.fused_evidence.infrastructure) ? run!.fused_evidence.infrastructure as Array<Record<string, unknown>> : [];
  return <State loading={loading} error={error} empty={!run}><section className="space-y-6"><div><p className="label">Phase 3</p><h1 className="mt-2 text-3xl font-bold">Infrastructure intelligence</h1><p className="mt-2 text-slate-400">Observed DNS, IP, GeoIP, provider, and correlation evidence for this forensic run.</p></div><div className="grid gap-4 md:grid-cols-2">{infrastructure.length ? infrastructure.map((item, index) => <div className="panel" key={`${String(item.ip)}-${index}`}><div className="flex justify-between gap-3"><strong>{String(item.domain || item.ip || "Observation")}</strong><Badge value={String(item.geoip_status || item.enrichment_status || item.status || "unknown")} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="label">IP</dt><dd>{String(item.ip || "—")}</dd></div><div><dt className="label">Location</dt><dd>{[item.city, item.country].filter(Boolean).join(", ") || "Unavailable"}</dd></div><div><dt className="label">Coordinates</dt><dd>{item.latitude && item.longitude ? `${item.latitude}, ${item.longitude}` : "Unavailable"}</dd></div><div><dt className="label">Timezone</dt><dd>{String(item.timezone || "Unavailable")}</dd></div></dl></div>) : <div className="panel text-slate-400">No infrastructure observations were available for this run.</div>}</div><div className="panel"><h2 className="font-semibold">Forensic report</h2><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-xs text-slate-400">{report ? report.report_markdown : "The report endpoint is unavailable or requires the configured API key."}</pre></div></section></State>;
}

export default function App() { return <Layout><Routes><Route path="/" element={<Dashboard />} /><Route path="/email-analysis" element={<EmailAnalysis />} /><Route path="/analyses/:analysisId" element={<AnalysisDetails />} /><Route path="/forensics/:runId" element={<Forensics />} /><Route path="/infrastructure/:runId" element={<Infrastructure />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes><footer className="mt-10 border-t border-slate-800 pt-4 text-xs text-slate-600">Backend API: {API_BASE_URL}</footer></Layout>; }
